//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGVE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int ClientID { get; set; }
        public string TourName { get; set; }
        public int EventID { get; set; }
        public System.DateTime EventDate { get; set; }
        public decimal Payment { get; set; }
        public System.DateTime DateBooked { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TourEvent TourEvent { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
